version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-db-backend
    depends_on:
      - db
   
    ports:
      - "8000:8000"
    restart: unless-stopped
    

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: 1234AAA
      POSTGRES_DB: Ex_batch
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      
volumes:
  pg_data:
